### PR TITLE
Skip metric with values as lists

### PR DESCRIPTION
**Pull request by InformatiQ**
metrics metrics with values with type list break collectd

### CODE REVIEW

**Comment by kamaradclimber** [comment]
@InformatiQ   could you please target the upstream repo instead of this one? It would be good to avoid maintaining additional forks

**Comment by InformatiQ** [comment]
actually there is a similar PR upstream since march, seems upstream is dead
How do you suggest we handle that case?

**Comment by pierrecdn** [comment]
+1, we could also open a separated PR upstream for this patch.

**Comment by InformatiQ** [comment]
This fork will be obsoleted when thosr PR are merged
https://github.com/klynch/collectd-marathon/pull/6
https://github.com/klynch/collectd-marathon/pull/3

**Pull request merged**
